# Generated by Django 3.2 on 2022-12-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221214_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlegenre',
            options={'verbose_name': 'Произведения и жанры', 'verbose_name_plural': 'Произведения и жанры'},
        ),
    ]
